### ISSUE TITLE
Upcoming Pickups first

### ISSUE THREAD

**Issue by D0nPiano** [yunity/foodsaving-frontend#160] opened 2016-12-02 11:26 UTC
Pickuplist should somehow only display upcoming pickups (or maybe one that was in the past), so that the user doesn't have to scroll the entrie page to find the next one.

**Comment by tiltec** [comment] 2016-12-02 11:31
Agree. I would modify the backend to only return future pickup dates: https://github.com/yunity/foodsaving-backend/issues/211 (with a different handling for historic data)
Therefore, no change needed in the frontend right now.

**Comment by alangecker** [comment] 2016-12-07 23:42
duplicate of #177 & #182

**Closed by alangecker** 2016-12-07 23:42 UTC
